src/Entity/Person.php
<?php

namespace App\Entity;

use App\Repository\PersonRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Validator as AppAssert;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PersonRepository::class)
 */
class Person
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prename;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     * @AppAssert\AgeConstraint()
     */
    private $birthdate;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrename(): ?string
    {
        return $this->prename;
    }

    public function setPrename(string $prename): self
    {
        $this->prename = $prename;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getAge(): ?int
    {
        if ($this->birthdate instanceof \DateTime) {
            $referenceDateTime = new \DateTime("now");

            return $referenceDateTime->diff($this->birthdate, true)->y;
        }

        return null;
    }
}

src/Form/ImportType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ImportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('attachment', FileType::class, [
                'label' => false,
            ])
            ->add('valider', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Form/PersonType.php
<?php

namespace App\Form;

use App\Entity\Person;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('prename')
            ->add('birthdate', DateTimeType::class, [
                'widget' => 'single_text',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Person::class,
        ]);
    }
}

src/Controller/PersonController.php
<?php

namespace App\Controller;

use App\Entity\Person;
use App\Form\ImportType;
use App\Form\PersonType;
use App\Repository\PersonRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use SplFileObject;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PersonController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function home()
    {
        return $this->render('index.html.twig');
    }

    #[Route('/person', name: 'person_index', methods: ['GET'])]
    public function index(PersonRepository $personRepository): Response
    {
        return $this->render('person/index.html.twig', [
            'people' => $personRepository->findBy([], ['name' => 'ASC']),
        ]);
    }

    #[Route('/person/new', name: 'person_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $person = new Person();
        $form = $this->createForm(PersonType::class, $person);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($person);
            $entityManager->flush();

            return $this->redirectToRoute('person_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('person/new.html.twig', [
            'person' => $person,
            'form' => $form,
        ]);
    }

    #[Route('/person/import', name: 'person_import', methods: ['GET', 'POST'])]
    public function import(Request $request, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ImportType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Récupération du fichier transmis
            $upload = $form['attachment']->getData();
            // Nouveau nom de fichier
            $file = sprintf('%s.%s', uniqid(), $upload->guessExtension());
            // Copie dans le dossier upload
            $upload->move(
                $this->getParameter('attachment_directory'),
                $file
            );
            // lecture du fichier
            $fileRead = new SplFileObject(sprintf('%s%s%s', $this->getParameter('attachment_directory'), \DIRECTORY_SEPARATOR, $file));
            $fileRead->setFlags(
                SplFileObject::READ_CSV |
                SplFileObject::SKIP_EMPTY |
                SplFileObject::DROP_NEW_LINE |
                SplFileObject::READ_AHEAD
            );
            $i = 0;
            while (false == $fileRead->eof()) {
                ++$i;
                if ($i <= 1) {
                    $fileArrayKey = $fileRead->fgetcsv();
                }
                if ($i >= 2) {
                    $fileArrayValue = $fileRead->fgetcsv();
                    $personData = array_combine($fileArrayKey, $fileArrayValue);
                    $person = new Person();
                    $person->setName($personData['name']);
                    $person->setPrename($personData['prename']);
                    $person->setBirthdate(DateTime::createFromFormat('d/m/Y', $personData['birthdate']));
                    $entityManager->persist($person);
                }
            }
            $entityManager->flush();

            return $this->redirectToRoute('person_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('person/import.html.twig', [
            'form' => $form,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/index.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="jumbotron text-center">
        <h1>Test WA</h1>
        <a href="{{ path('person_new') }}" class="btn btn-primary">Ajouter une personne</a>
        <a href="{{ path('person_index') }}" class="btn btn-secondary">Visualiser toutes les personnes</a>
    </div>
{% endblock %}

templates/person/_form.html.twig
{{ form_start(form) }}
<div class="container">
    <div class="row align-items-center pb-4">
        <div class="col">{{ form_row(form.name) }}</div>
        <div class="col">{{ form_row(form.prename) }}</div>
        <div class="col">{{ form_row(form.birthdate) }}</div>
    </div>
</div>
    {{ form_widget(form) }}
    <div class="d-grid gap-2 col-1 mx-auto">
        <button class="btn btn-primary">{{ button_label|default('Valider') }}</button>
    </div>

{{ form_end(form) }}

templates/person/import.html.twig
{% extends "base.html.twig" %}

{% block title %}Import{% endblock %}

{% block body %}
    <h1>Importer un fichier CSV</h1>

    {{ form(form) }}

{% endblock %}

templates/person/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Index{% endblock %}

{% block body %}
    <h1>Personnes enregistrées</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Prename</th>
                <th>Birthdate</th>
                <th>Age</th>
            </tr>
        </thead>
        <tbody>
        {% for person in people %}
            <tr>
                <td>{{ person.id }}</td>
                <td>{{ person.name }}</td>
                <td>{{ person.prename }}</td>
                <td>{{ person.birthdate ? person.birthdate|date('Y-m-d') : '' }}</td>
                <td>{{ person.age }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="d-grid gap-2 col-6 mx-auto">
        <a href="{{ path('person_new') }}" class="btn btn-primary">Create new</a>
        <a href="{{ path('person_import') }}" class="btn btn-success">Import CSV</a>
    </div>
{% endblock %}

templates/person/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Person{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1 class="pt-2 pb-4">Ajouter une nouvelle personne</h1>

        {{ include('person/_form.html.twig') }}

        <div class="d-grid gap-2 col-1 mx-auto">
            <a href="{{ path('person_index') }}" class="btn btn-secondary">Back to list</a>
        </div>

    </div>
{% endblock %}